# Site settings
title: Reth Radin
email: radin.reth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi everyone!
  My name is Radin. I am a software engineer.
  I love coding, traveling and listening to music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: radinreth
github_username:  radinreth

# Build settings
markdown: kramdown
